#!/usr/bin/ruby
#
# This file is part of CPEE-SHIFTING.
#
# CPEE-SHIFTING is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# CPEE-SHIFTING is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with CPEE-SHIFTING (file COPYING in the main directory). If not, see
# <http://www.gnu.org/licenses/>.

require 'rubygems'
if File.exist? File.join(__dir__,'cpee-shifting','implementation.rb')
  require_relative 'cpee-shifting/implementation'
else
  require 'cpee-shifting/implementation'
end

options = {
  :host => 'localhost',
  :port => 9319,
  :secure => false
}

Riddl::Server.new(CPEE::Shifting::SERVER, options) do
  accessible_description true
  cross_site_xhr true

  @riddl_opts[:log_dir] ||= File.join(__dir__,'logs')

  use CPEE::Shifting::implementation(@riddl_opts)
end.loop!
